FROM alpine AS certs
RUN apk update && apk add ca-certificates

FROM golang:1.23 AS build
WORKDIR /app
COPY . .
RUN go build -o tls-exterminator . 

FROM busybox
WORKDIR /app
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
COPY --from=build /app/tls-exterminator /app/tls-exterminator
COPY ./test-server/server.crt /etc/ssl/certs/server.crt

CMD ["/app/tls-exterminator"]
