services:
  host1:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    environment:
      - HOST=host1
  host2:
    build:
      context: .
      dockerfile: Dockerfile.test-server
    environment:
      - HOST=host2
  tls1:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5000:5000"
    environment:
      - "CONFIG=5000:host1"
  tls2:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5001:5001"
    environment:
      - "CONFIG=5001:host2"